services:
  - type: web
    name: pos-project
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: POS_PIN
        sync: false
      - key: REGISTER_PIN
        sync: false
      - key: BACK_OFFICE_PIN
        sync: false
